sudo: false
language: go
go:
- 1.11.x
install:
- go get github.com/golang/dep/cmd/dep
- dep ensure
notifications:
  email: false
script:
- go build

deploy:
  provider: releases
  api_key:
    secure: sOnlA8nCwrk/fa2NbkOwVG710xOCKQo4hVo+sVF3783nkf+lEK6Waz2jxplFQzZo/nq08qoVDK53gidR0DRrxNw5CKjG1w5Bap05sca3ruMcv9rHI2PhwSCSpOM8PRf1LPZRRbeWr8NtL8hwSaEh8zDzzRmBchmmU/Yu1BhWpDtQ6Skn/uTjIlhiR/pDsRbKM97nS6gbuGdNTnlf5Em2PaTzGzKOa55y9vSF/zacHzRBIqQYVSWSDyjes9m9x4QyPcmgPJrUAPTJSPWN2wuPEXGiyx6ncc4JK15jO4y37FbOPiQi1CrnaotT0o3q3p3UHn6ApPUClrZBZlD2nr6UskMBDKdFW+U/lPH1Zu/e7zz90o2IifDtkWtNmUWEqfVjIe3Tx5r12YE4VDO17O6XIFRZnvi8RZ6mMF4SUqAgQ9dxPTNI3wRMss16BG9yYDU6IPTQaAc/rdHQvQIn4Ii/isd9eV2bZ9uxbnHPdQPfObaLtnONjJXGZCCnzgPr/jWG1M8LMbuYqQFHSwzNLUbvFAooGPN/7o5JSB//yCwLhxiLcI2/aV1QxSTaH4mE0kAiKzLYy4mbfjfYW/Fz+0civfqcstkb27O+Eov1pfhE7REEln6tDEIDKRwhHQd3jQWayEDVAMdSJq5DpYVIon1u/Zb+/n590HOPOkuz6Yfe0eE=
  file: goose
  on:
    repo: HashLoad/goose
    tags: true
