sudo: false
language: go
go:
  - 1.11.x
install:
  - go get github.com/golang/dep/cmd/dep
  - dep ensure
notifications:
  email: false
script:
  - go build -o goose cmd/goose/app.go
deploy:
  provider: releases
  api_key:
    secure: BNxzqNIQyV1Y8Y8KLt0DkR3SybU1ykpr4ICrGSfCoPQHKMF9SxDx3N88SYIeYspPdjYP38BUNv525d7bOooMuS/iLka79C40EU6CNkUXzBhYDXxAIyoYl/ztPyVbingMT5J0AO04x0cZHuts6TaG7QmSKeEUDrZG/yl69AbQEdnMDR13/8MAJu1cbHXngpE4ydUUqtbzB6UHDmiBgoBOF6LFVWG2qC9U/FQFIZhlO72z9uuhw76J6KG1zIJoPYsS3F2BgxJwJJo4UnXE6MjtkaGVx8/zQ8K9CayLvyWFZWp9Gx1Fn9aZNXb08GsWLFdgsUCIq9BSoO4Fv3OF9FLcIpIw6H6lIQCFFdF2TIhHnb0cmey/W8YUQXvw+Cyzv96yuf2jGZmSsdW2tbIH/ewcCjNr/q5LeDEdS8zFaiB+UdHe71rL9bCIO2U9vgT0V5WiA0zjtaFEAtBVfe+Gp31N7ZhcqfVDFEe5RVTwOrOP9fceWp94Gcls162D607Qro43WJG5eoC5NoM7X5w3LOn9W0ys+0hzimbJn+gsfNYCOEUNO+B9NJAePgbp3B3NLmfp1uycc4+TFjO4KLsyuArZs08QkBiyXogO2HEAgKzntanAJzzaalNyfKCdetmaqTGCVDLl8pURWBVR1o4l9JLRBXo3puvZwKaAD4R6JuWYNK8=
  file:
    - goose
  skip_cleanup: true
  on:
    tags: true
    repo: HashLoad/goose
