sudo: false
language: go
go:
- 1.11.x
install:
- go get github.com/golang/dep/cmd/dep
- dep ensure
notifications:
  email: false
script:
- go build
deploy:
  provider: releases
  api_key:
    secure: E1aMzQR/XISx3esdgGW8b/qC9VnUUPGMrhhJhQ7sa5yt1QmICvrLp+VohdhwymXdZxvoUaA7C00LV+qTC5VsY8B9ljNMKaxv3nv+pGF5lpk9x6Tm11H+8+W0wX8571r2sBoW3h6qr653P3Ija7+Y7DFzkd6XFD34tNqGsEYwjNiFJYmomQSeUw/zz43/6XLYinfdxTTrMikoTwcEeZ/3BXlcI7a57h7jtlcZxCVWYNVvY4KLlbLf247YU23+1OY+Z/RV3FGqq63qPz3qlzKyVX2vctcc8bhfZQmGjQwRmoKfV0wl7RHC0KH0PAVLKcdljbd2zDM7RozglL1yb4+rNMWY0wEY2CcmdzmCVvUHRfSV7bC6A1bMU9dozpTdTfyk3yI6waKR7nAoxTOOfXcSbO4+LOZaVKIIrQEggJelPLddSnSWP+y+l6GQZ0WO6aHVSeog9q5V48/qio4EF8gmJBMtp4OOTYtC4uPnr6KjJUQwNWubzBiuRK+T+Fm1Ss1a16qiyZxG4wTYSRQ/qdSpQZK/FafA9He+JTCMALGHZeQ0wisAR7TTV9NYdZ/cOFpgjZzaLfveggWerjN7lOCWaLeOHnzmwLYVAR2JWmqTt0mxgoeqbUPSg+cM2XbRzITo0j5Bw4xaKdYtx6QxfjVZMahG21xKt+itgpOVIfdkOIg=
  file: goose
  on:
    repo: HashLoad/goose
    tags: true
