[[constraint]]
  name = "github.com/go-sql-driver/mysql"
  version = "^1.3.0"

[[constraint]]
  branch = "master"
  name = "github.com/lib/pq"

[[constraint]]
  name = "gopkg.in/goracle.v2"
  version = "2.18.2"
